
void copy_v4_to_v5(eeprom_data_format_t *v4,eeprom_data_format_t *v5)

{
  int iVar1;
  edf_u8_set p_Var2;
  edf_u16_set p_Var3;
  edf_i8_set p_Var4;
  eeprom_data_format_t *v5_local;
  eeprom_data_format_t *v4_local;
  char board_name [40];
  char chip_tech [2];
  char hashboard_index [16];
  char hashboard_ctrl_code [16];
  char temp_sensor_type [16];
  char chip_ftversion [16];
  char chip_bin [16];
  char chip_marking [16];
  char chip_die [16];
  char factory_job [32];
  char board_sn [32];
  size_t len;
  
  len = 0;
  p_Var2 = v5->enc_algorithm_set;
  iVar1 = (*v4->enc_algorithm_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  p_Var2 = v5->enc_key_version_set;
  iVar1 = (*v4->enc_key_version_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  memset(board_sn,0,0x20);
  len = 0x20;
  (*v4->board_sn_get)(v4,board_sn,&len);
  (*v5->board_sn_set)(v5,board_sn,&len);
  len = 0x10;
  memset(chip_die,0,0x10);
  (*v4->chip_die_get)(v4,chip_die,&len);
  (*v5->chip_die_set)(v5,chip_die,&len);
  len = 0x10;
  memset(chip_marking,0,0x10);
  (*v4->chip_marking_get)(v4,chip_marking,&len);
  (*v5->chip_marking_set)(v5,chip_marking,&len);
  len = 0x10;
  memset(chip_ftversion,0,0x10);
  (*v4->ft_version_get)(v4,chip_ftversion,&len);
  (*v5->ft_version_set)(v5,chip_ftversion,&len);
  len = 2;
  memset(chip_tech,0,2);
  (*v4->chip_tech_get)(v4,chip_tech,&len);
  (*v5->chip_tech_set)(v5,chip_tech,&len);
  p_Var2 = v5->chip_bin_set;
  iVar1 = (*v4->chip_bin_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  (*v5->asic_sensor_type_set)(v5,'\0');
  (*v5->pic_sensor_type_set)(v5,'\0');
  p_Var3 = v5->pcb_version_set;
  iVar1 = (*v4->pcb_version_get)(v4);
  (*p_Var3)(v5,(uint16_t)iVar1);
  p_Var3 = v5->bom_version_set;
  iVar1 = (*v4->bom_version_get)(v4);
  (*p_Var3)(v5,(uint16_t)iVar1);
  p_Var2 = v5->pt1_result_set;
  iVar1 = (*v4->pt1_result_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  p_Var2 = v5->pt1_count_set;
  iVar1 = (*v4->pt1_count_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  p_Var2 = v5->pt2_result_set;
  iVar1 = (*v4->pt2_result_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  p_Var2 = v5->pt2_count_set;
  iVar1 = (*v4->pt2_count_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  len = 0x28;
  memset(board_name,0,0x28);
  (*v4->board_name_get)(v4,board_name,&len);
  (*v5->board_name_set)(v5,board_name,&len);
  len = 0x20;
  memset(factory_job,0,0x20);
  (*v4->factory_job_get)(v4,factory_job,&len);
  (*v5->factory_job_set)(v5,factory_job,&len);
  p_Var3 = v5->voltage_set;
  iVar1 = (*v4->voltage_get)(v4);
  (*p_Var3)(v5,(uint16_t)iVar1);
  p_Var3 = v5->frequency_set;
  iVar1 = (*v4->frequency_get)(v4);
  (*p_Var3)(v5,(uint16_t)iVar1);
  p_Var3 = v5->nonce_rate_set;
  iVar1 = (*v4->nonce_rate_get)(v4);
  (*p_Var3)(v5,(uint16_t)iVar1);
  p_Var4 = v5->pcb_temp_in_set;
  iVar1 = (*v4->pcb_temp_in_get)(v4);
  (*p_Var4)(v5,(int8_t)iVar1);
  p_Var4 = v5->pcb_temp_out_set;
  iVar1 = (*v4->pcb_temp_out_get)(v4);
  (*p_Var4)(v5,(int8_t)iVar1);
  p_Var2 = v5->test_version_set;
  iVar1 = (*v4->test_version_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  p_Var2 = v5->test_standard_set;
  iVar1 = (*v4->test_standard_get)(v4);
  (*p_Var2)(v5,(uint8_t)iVar1);
  return;
}

