
void Curl_flush_cookies(int param_1,int param_2)

{
  bool bVar1;
  int iVar2;
  FILE *__s;
  int *piVar3;
  char *__filename;
  
  if (*(int *)(param_1 + 0x34c) == 0) {
    if ((param_2 != 0) && (*(int *)(param_1 + 0x460) != 0)) {
      curl_slist_free_all();
      *(undefined4 *)(param_1 + 0x460) = 0;
    }
    Curl_share_lock(param_1,2,2);
  }
  else {
    if (*(int *)(param_1 + 0x460) != 0) {
      Curl_cookie_loadfiles();
    }
    Curl_share_lock(param_1,2,2);
    piVar3 = *(int **)(param_1 + 0x468);
    __filename = *(char **)(param_1 + 0x34c);
    if ((piVar3 != (int *)0x0) && (piVar3[3] != 0)) {
      remove_expired(piVar3);
      iVar2 = curl_strequal("-",__filename);
      if (iVar2 == 0) {
        __s = fopen64(__filename,"w");
        bVar1 = false;
        if (__s == (FILE *)0x0) {
LAB_0003f948:
          Curl_infof(param_1,"WARNING: failed to save cookies in %s\n",
                     *(undefined4 *)(param_1 + 0x34c));
          goto LAB_0003f896;
        }
      }
      else {
        bVar1 = true;
        __s = stdout;
      }
      fwrite("# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n"
             ,1,0x88,__s);
      for (piVar3 = (int *)*piVar3; piVar3 != (int *)0x0; piVar3 = (int *)*piVar3) {
        if (piVar3[5] != 0) {
          iVar2 = get_netscape_format(piVar3);
          if (iVar2 == 0) {
            curl_mfprintf(__s,"#\n# Fatal libcurl error\n");
            if (!bVar1) {
              fclose(__s);
            }
            goto LAB_0003f948;
          }
          curl_mfprintf(__s,"%s\n",iVar2);
          (*Curl_cfree)(iVar2);
        }
      }
      if (!bVar1) {
        fclose(__s);
      }
    }
  }
LAB_0003f896:
  if (param_2 != 0) {
    if (*(int *)(param_1 + 0x48) == 0) {
      iVar2 = *(int *)(param_1 + 0x468);
    }
    else {
      iVar2 = *(int *)(param_1 + 0x468);
      if (iVar2 == *(int *)(*(int *)(param_1 + 0x48) + 0x2c)) goto LAB_0003f8b0;
    }
    Curl_cookie_cleanup(iVar2);
  }
LAB_0003f8b0:
  Curl_share_unlock(param_1,2);
  return;
}

