/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'bitmain_axi.ko'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 2 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 3 */
typedef __n64 int8x8_t;

/* 4 */
typedef __n64 uint8x8_t;

/* 5 */
typedef __n64 int16x4_t;

/* 6 */
typedef __n64 int32x2_t;

/* 7 */
typedef __n64 uint16x4_t;

/* 8 */
typedef __n64 uint32x2_t;

/* 9 */
typedef __n128 int8x16_t;

/* 10 */
typedef __n128 int16x8_t;

/* 11 */
typedef __n128 int32x4_t;

/* 12 */
typedef __n128 int64x2_t;

/* 13 */
typedef __n128 uint8x16_t;

/* 14 */
typedef __n128 uint16x8_t;

/* 15 */
typedef __n128 uint32x4_t;

/* 16 */
typedef __n128 uint64x2_t;

/* 17 */
typedef __n64 poly8x8_t;

/* 18 */
typedef __n64 poly16x4_t;

/* 19 */
typedef __n128 poly16x8_t;

/* 20 */
typedef __n128 poly8x16_t;

/* 21 */
typedef __n64 float16x4_t;

/* 22 */
typedef __n64 float32x2_t;

/* 23 */
typedef __n128 float16x8_t;

/* 24 */
typedef __n128 float32x4_t;

/* 25 */
typedef __n128 float64x2_t;

/* 26 */
typedef __n128 poly128_t;

/* 27 */
typedef int16x4_t int16x2_t;

/* 28 */
typedef uint16x4_t uint16x2_t;

/* 29 */
typedef float16x4_t float16x2_t;

