/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'bmminer'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

union $1C4035FDEAFFF0FCE26E66A96F6BBEB4;
struct $44840292B0FD4432816E14C2BB6B9957;
struct siginfo;
struct sockaddr;
struct $6ECA53571B8FCC125A3088582131FB6E;
union $F85E194B51CBDC38F209555F4162D10C;
union $738A8E8AC168E5B4B1A53622C9D7048F;

/* 1 */
struct Elf32_Sym
{
  unsigned __int32 st_name __offset(OFF32,0x1112C);
  unsigned __int32 st_value __off;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 3 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 4 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file __offset(OFF32,0x1112C);
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 6 */
struct Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name __offset(OFF32,0x1112C);
  unsigned __int32 vna_next;
};

/* 7 */
typedef unsigned int size_t;

/* 8 */
typedef unsigned __int64 UDItype;

/* 9 */
typedef unsigned int USItype;

/* 10 */
typedef double DFtype;

/* 11 */
struct complex_double
{
  double real;
  double imag;
};

/* 12 */
struct complex_float
{
  float real;
  float imag;
};

/* 13 */
typedef unsigned int sizetype;

/* 14 */
typedef __int64 DItype;

/* 15 */
typedef union $1C4035FDEAFFF0FCE26E66A96F6BBEB4 pthread_cond_t;

/* 17 */
struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E
{
  int __lock;
  unsigned int __futex;
  unsigned __int64 __total_seq;
  unsigned __int64 __wakeup_seq;
  unsigned __int64 __woken_seq;
  void *__mutex;
  unsigned int __nwaiters;
  unsigned int __broadcast_seq;
};

/* 16 */
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4
{
  struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E __data;
  char __size[48];
  __int64 __align;
};

/* 19 */
typedef struct $44840292B0FD4432816E14C2BB6B9957 __sigset_t;

/* 18 */
typedef __sigset_t sigset_t;

/* 20 */
struct $44840292B0FD4432816E14C2BB6B9957
{
  unsigned int __val[32];
};

/* 23 */
typedef void (*__sighandler_t)(int);

/* 24 */
typedef struct siginfo siginfo_t;

/* 22 */
union sigaction::$8A6CDC2F5AA8DF854CEC54DCAF095C68
{
  __sighandler_t sa_handler;
  void (*sa_sigaction)(int, siginfo_t *, void *);
};

/* 21 */
struct sigaction
{
  union sigaction::$8A6CDC2F5AA8DF854CEC54DCAF095C68 __sigaction_handler;
  __sigset_t sa_mask;
  int sa_flags;
  void (*sa_restorer)(void);
};

/* 28 */
typedef int __pid_t;

/* 29 */
typedef unsigned int __uid_t;

/* 27 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$DDF278A5B88F81FEC3CBEE828E282CB3
{
  __pid_t si_pid;
  __uid_t si_uid;
};

/* 32 */
union sigval
{
  int sival_int;
  void *sival_ptr;
};

/* 31 */
typedef union sigval sigval_t;

/* 30 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$F43D85AC31CEBD8CC07B08111ABDF065
{
  int si_tid;
  int si_overrun;
  sigval_t si_sigval;
};

/* 33 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$002955E8B5DE3B92E30DFEF7AB65BFE2
{
  __pid_t si_pid;
  __uid_t si_uid;
  sigval_t si_sigval;
};

/* 35 */
typedef int __clock_t;

/* 34 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$353EAF26536A4016665766004ADC0BD6
{
  __pid_t si_pid;
  __uid_t si_uid;
  int si_status;
  __clock_t si_utime;
  __clock_t si_stime;
};

/* 36 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$394784BEE55B7018BCA7354475FB2ABC
{
  void *si_addr;
};

/* 37 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$534EC22A0813C1325C3E7D3262B5A8D3
{
  int si_band;
  int si_fd;
};

/* 26 */
union siginfo::$0A533C95F56D7198FDCBF4ED772C5A43
{
  int _pad[29];
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$DDF278A5B88F81FEC3CBEE828E282CB3 _kill;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$F43D85AC31CEBD8CC07B08111ABDF065 _timer;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$002955E8B5DE3B92E30DFEF7AB65BFE2 _rt;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$353EAF26536A4016665766004ADC0BD6 _sigchld;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$394784BEE55B7018BCA7354475FB2ABC _sigfault;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$534EC22A0813C1325C3E7D3262B5A8D3 _sigpoll;
};

/* 25 */
struct siginfo
{
  int si_signo;
  int si_errno;
  int si_code;
  union siginfo::$0A533C95F56D7198FDCBF4ED772C5A43 _sifields;
};

/* 39 */
typedef unsigned int __socklen_t;

/* 38 */
typedef __socklen_t socklen_t;

/* 40 */
struct addrinfo
{
  int ai_flags;
  int ai_family;
  int ai_socktype;
  int ai_protocol;
  socklen_t ai_addrlen;
  struct sockaddr *ai_addr;
  char *ai_canonname;
  struct addrinfo *ai_next;
};

/* 42 */
typedef unsigned __int16 sa_family_t;

/* 41 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 43 */
typedef struct $6ECA53571B8FCC125A3088582131FB6E fd_set;

/* 45 */
typedef int __fd_mask;

/* 44 */
struct $6ECA53571B8FCC125A3088582131FB6E
{
  __fd_mask __fds_bits[32];
};

/* 47 */
typedef int __time_t;

/* 48 */
typedef int __suseconds_t;

/* 46 */
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};

/* 49 */
typedef union $F85E194B51CBDC38F209555F4162D10C pthread_mutex_t;

/* 54 */
struct __pthread_internal_slist
{
  struct __pthread_internal_slist *__next;
};

/* 53 */
typedef struct __pthread_internal_slist __pthread_slist_t;

/* 52 */
union $::__pthread_mutex_s::$30DFB618E49C377A3D62C6584A4CBE95
{
  int __spins;
  __pthread_slist_t __list;
};

/* 51 */
struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  int __kind;
  unsigned int __nusers;
  union
  {
    int __spins;
    __pthread_slist_t __list;
  };
};

/* 50 */
union $F85E194B51CBDC38F209555F4162D10C
{
  struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s __data;
  char __size[24];
  int __align;
};

/* 55 */
typedef union $738A8E8AC168E5B4B1A53622C9D7048F pthread_rwlock_t;

/* 57 */
struct $738A8E8AC168E5B4B1A53622C9D7048F::$D6587128ED4C013AF36DCCA432989BD5
{
  int __lock;
  unsigned int __nr_readers;
  unsigned int __readers_wakeup;
  unsigned int __writer_wakeup;
  unsigned int __nr_readers_queued;
  unsigned int __nr_writers_queued;
  unsigned int __flags;
  int __writer;
};

/* 56 */
union $738A8E8AC168E5B4B1A53622C9D7048F
{
  struct $738A8E8AC168E5B4B1A53622C9D7048F::$D6587128ED4C013AF36DCCA432989BD5 __data;
  char __size[32];
  int __align;
};

/* 59 */
typedef int __jmp_buf[6];

/* 58 */
struct __jmp_buf_tag
{
  __jmp_buf __jmpbuf;
  int __mask_was_saved;
  __sigset_t __saved_mask;
};

/* 60 */
typedef unsigned int pthread_t;

/* 61 */
struct timespec
{
  __time_t tv_sec;
  int tv_nsec;
};

/* 62 */
struct sysinfo
{
  int uptime;
  unsigned int loads[3];
  unsigned int totalram;
  unsigned int freeram;
  unsigned int sharedram;
  unsigned int bufferram;
  unsigned int totalswap;
  unsigned int freeswap;
  unsigned __int16 procs;
  unsigned __int16 pad;
  unsigned int totalhigh;
  unsigned int freehigh;
  unsigned int mem_unit;
  char _f[8];
};

/* 63 */
typedef __time_t time_t;

/* 66 */
typedef unsigned __int64 __u_quad_t;

/* 65 */
typedef __u_quad_t __dev_t;

/* 67 */
typedef unsigned int __ino_t;

/* 68 */
typedef unsigned int __mode_t;

/* 69 */
typedef unsigned int __nlink_t;

/* 70 */
typedef unsigned int __gid_t;

/* 71 */
typedef int __off_t;

/* 72 */
typedef int __blksize_t;

/* 73 */
typedef int __blkcnt_t;

/* 64 */
struct stat
{
  __dev_t st_dev;
  unsigned __int16 __pad1;
  __ino_t st_ino;
  __mode_t st_mode;
  __nlink_t st_nlink;
  __uid_t st_uid;
  __gid_t st_gid;
  __dev_t st_rdev;
  unsigned __int16 __pad2;
  __off_t st_size;
  __blksize_t st_blksize;
  __blkcnt_t st_blocks;
  struct timespec st_atim;
  struct timespec st_mtim;
  struct timespec st_ctim;
  unsigned int __unused4;
  unsigned int __unused5;
};

/* 75 */
typedef void *__builtin_va_list;

/* 74 */
typedef __builtin_va_list __gnuc_va_list;

/* 76 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 77 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 78 */
typedef __n64 int8x8_t;

/* 79 */
typedef __n64 uint8x8_t;

/* 80 */
typedef __n64 int16x4_t;

/* 81 */
typedef __n64 int32x2_t;

/* 82 */
typedef __n64 uint16x4_t;

/* 83 */
typedef __n64 uint32x2_t;

/* 84 */
typedef __n128 int8x16_t;

/* 85 */
typedef __n128 int16x8_t;

/* 86 */
typedef __n128 int32x4_t;

/* 87 */
typedef __n128 int64x2_t;

/* 88 */
typedef __n128 uint8x16_t;

/* 89 */
typedef __n128 uint16x8_t;

/* 90 */
typedef __n128 uint32x4_t;

/* 91 */
typedef __n128 uint64x2_t;

/* 92 */
typedef __n64 poly8x8_t;

/* 93 */
typedef __n64 poly16x4_t;

/* 94 */
typedef __n128 poly16x8_t;

/* 95 */
typedef __n128 poly8x16_t;

/* 96 */
typedef __n64 float16x4_t;

/* 97 */
typedef __n64 float32x2_t;

/* 98 */
typedef __n128 float16x8_t;

/* 99 */
typedef __n128 float32x4_t;

/* 100 */
typedef __n128 float64x2_t;

/* 101 */
typedef __n128 poly128_t;

/* 102 */
typedef int16x4_t int16x2_t;

/* 103 */
typedef uint16x4_t uint16x2_t;

/* 104 */
typedef float16x4_t float16x2_t;

